<?xml version="1.0" encoding="utf-8"?><Database Name="MemberCDAC" Class="MemberCDAC_DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SAIBABA-PC\SAIBABA;Initial Catalog=MemberCDAC;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MemberCDACConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblMembers" Member="tblMembers">
    <Type Name="tblMember">
      <Column Name="MemberID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="place" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="joindate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>